services:
  - type: web
    name: 75-hard
    buildCommand: npm install && npm run build
    staticPublishPath: ./web-build  # Changed from ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html