import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#000',
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    minHeight: '100%',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#000',
  },
  scrollView: {
    backgroundColor: '#000',
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingVertical: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  mainTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#ddd5ca',
    marginBottom: 24,
    fontFamily: 'Inter',
  },
  card: {
    backgroundColor: '#ddd5ca',
    borderRadius: 24,
    width: '100%',
    maxWidth: 600,
    padding: 24,
    borderWidth: 2,
    borderColor: '#000',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#000',
  },
  addButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    color: '#000',
  },
  addButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ddd5ca',
    borderWidth: 2,
    borderColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000',
  },
  taskList: {
    gap: 16,
  },
  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    height: 44,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#000',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#000',
    borderColor: '#000',
  },
  taskText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
  },
  taskTextCompleted: {
    textDecorationLine: 'line-through',
    opacity: 0.5,
  },
  actions: {
    flexDirection: 'row',
    gap: 4,
    opacity: 1,
    width: 64,
    justifyContent: 'flex-end',
  },
  actionsHidden: {
    opacity: 0,
    pointerEvents: 'none',
  },
  actionButton: {
    width: 28,
    height: 28,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000',
  },
  deleteButton: {
    backgroundColor: '#ddd5ca',
    borderWidth: 2,
    borderColor: '#000',
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#000',
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  gridContainer: {
    marginTop: 32,
    borderTopWidth: 1,
    borderTopColor: '#00000020',
    paddingTop: 32,
  },
  gridTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
    marginBottom: 16,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  gridSquare: {
    width: 32,
    height: 32,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#000',
  },
  gridSquareCompleted: {
    backgroundColor: '#000',
    borderColor: '#000',
  },
  gridSquareCurrent: {
    borderColor: '#000',
    borderWidth: 2,
  },
  gridSquareUpcoming: {
    borderColor: '#000',
    opacity: 0.3,
  },
  gridSquareText: {
    fontSize: 12,
    color: '#000',
    fontWeight: '500',
  },
  gridSquareTextCompleted: {
    color: '#ddd5ca',
    fontWeight: '600',
  },
  gridSquareTextCurrent: {
    color: '#000',
  },
  dayControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  dayControlButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ddd5ca',
    borderWidth: 2,
    borderColor: '#000',
    opacity: 1,
  },
  dayControlButtonDisabled: {
    opacity: 0.3,
  },
  resetContainer: {
    marginTop: 32,
    borderTopWidth: 1,
    borderTopColor: '#00000020',
    paddingTop: 32,
    alignItems: 'center',
  },
  resetButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: '#ddd5ca',
    borderWidth: 2,
    borderColor: '#000',
  },
  resetButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },
});